// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"changeTitlePosition","status":false,"description":"","parameters":{}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}}
];
