// Generated by RPG Maker.
// Do not edit this file directly.
/**
 * ide导出的脚本数据，会在游戏启动后被引擎加载
 * @type {*[]}
 */
var $plugins =
[
{"name":"changeTitlePosition","status":false,"description":"","parameters":{}},
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}}
];
